# @file
# Sign EFI images and generate the test-data C files for the Image Verification unit test
# application.
#
# Given one unsigned EFI image per architecture, this script:
#   1. Generates a certificate chain (root CA -> intermediate CA -> leaf) and a second
#      independent self-signed signer with openssl.
#   2. Signs each image with the leaf certificate, embedding the intermediate + root chain,
#      and additionally with signer 2 for the dual-signed image (appending a second
#      WIN_CERTIFICATE) using sbsign.
#   3. Computes the Authenticode SHA-256 digest of each image, matching the hash that
#      SecurityPkg's DxeImageVerificationLib (HashPeImage) computes.
#   4. Emits the per-architecture C files X64/TestData.c and Aarch64/TestData.c, each
#      containing that architecture's images, digests, and the leaf / intermediate / root /
#      signer 2 certificates.
#
# Requires openssl and sbsign (sbsigntools) on PATH (or pass --openssl/--sbsign).
# sbsign ships with sbsigntools (Linux; use WSL on Windows).
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

import argparse
import hashlib
import os
import shutil
import struct
import subprocess
import sys
import tempfile

FILE_HEADER = """\
/** @file
    Test data for the Image Verification unit test application.

    This file is GENERATED by GenTestData.py. Do not edit by hand; rerun the script against
    the desired binaries to regenerate it.

    Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#include "TestData.h"
"""


def emit_array(symbol, description, data):
    """Render one byte array and its size symbol as C source text.

    The returned text contains a short comment block, a CONST UINT8 array, and
    a matching CONST UINTN size definition.
    """
    lines = []
    lines.append("")
    lines.append("//")
    lines.append(f"// {description}")
    lines.append("//")
    lines.append(f"CONST UINT8  {symbol}[] = {{")
    if len(data) == 0:
        # An empty array is not valid C; keep a single zero byte placeholder.
        data = b"\x00"
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("  " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append(f"CONST UINTN  {symbol}Size = sizeof ({symbol});")
    return "\n".join(lines) + "\n"


def read_file(path):
    """Read a file as bytes and return its contents."""
    with open(path, "rb") as handle:
        return handle.read()


def write_c_file(path, arrays):
    """Write a generated C file for the provided arrays.

    Each array entry is a tuple of (symbol, description, data). The file is
    emitted with CRLF line endings to match EDK2 source formatting.
    """
    body = FILE_HEADER
    for symbol, description, data in arrays:
        body += emit_array(symbol, description, data)

    # Normalize to CRLF line endings per EDK2 coding standards, then write in
    # binary mode so newlines are not translated again by the platform.
    body = body.replace("\r\n", "\n").replace("\n", "\r\n")

    output_dir = os.path.dirname(path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(path, "wb") as handle:
        handle.write(body.encode("ascii"))

    print(f"Wrote {path}")


def run(cmd):
    """Run a subprocess command and require a zero exit status."""
    subprocess.run(cmd, check=True)


def tool_path(name, override):
    """Resolve the path to a required external tool.

    An explicit override wins. Otherwise PATH is searched. The process exits
    with a descriptive error if the tool cannot be found.
    """
    path = override or shutil.which(name)
    if path is None:
        sys.exit(f"error: required tool '{name}' was not found on PATH; install it or pass --{name} PATH")
    return path


def generate_signer(openssl, workdir, stem, common_name):
    """Create a self-signed RSA test signer.

    Returns a tuple of (key_pem_path, cert_pem_path, cert_der_bytes).
    """
    key_pem = os.path.join(workdir, stem + ".key.pem")
    cert_pem = os.path.join(workdir, stem + ".cert.pem")
    cert_der = os.path.join(workdir, stem + ".cert.der")
    run([
        openssl, "req", "-x509", "-newkey", "rsa:2048", "-sha256",
        "-keyout", key_pem, "-out", cert_pem, "-days", "3650",
        "-nodes", "-subj", "/CN=" + common_name,
    ])
    run([openssl, "x509", "-in", cert_pem, "-outform", "DER", "-out", cert_der])
    return key_pem, cert_pem, read_file(cert_der)


def read_text(path):
    """Read a text file and return its contents as a string."""
    with open(path, "r") as handle:
        return handle.read()


def write_text(path, text):
    """Write the provided string to a text file."""
    with open(path, "w") as handle:
        handle.write(text)


def generate_root_ca(openssl, workdir, stem, common_name):
    """Create a self-signed RSA root CA certificate.

    Returns a tuple of (key_pem_path, cert_pem_path, cert_der_bytes).
    """
    key_pem = os.path.join(workdir, stem + ".key.pem")
    cert_pem = os.path.join(workdir, stem + ".cert.pem")
    cert_der = os.path.join(workdir, stem + ".cert.der")
    run([
        openssl, "req", "-x509", "-newkey", "rsa:2048", "-sha256",
        "-keyout", key_pem, "-out", cert_pem, "-days", "3650", "-nodes",
        "-subj", "/CN=" + common_name,
        "-addext", "basicConstraints=critical,CA:TRUE",
        "-addext", "keyUsage=critical,keyCertSign,cRLSign",
    ])
    run([openssl, "x509", "-in", cert_pem, "-outform", "DER", "-out", cert_der])
    return key_pem, cert_pem, read_file(cert_der)


def generate_signed_cert(openssl, workdir, stem, common_name, ca_key, ca_cert, is_ca):
    """Create an RSA certificate signed by the given CA.

    is_ca selects whether the new certificate is itself a CA (an intermediate)
    or a leaf code-signing certificate. Returns
    (key_pem_path, cert_pem_path, cert_der_bytes).
    """
    key_pem = os.path.join(workdir, stem + ".key.pem")
    csr_pem = os.path.join(workdir, stem + ".csr.pem")
    cert_pem = os.path.join(workdir, stem + ".cert.pem")
    cert_der = os.path.join(workdir, stem + ".cert.der")
    ext_file = os.path.join(workdir, stem + ".ext")

    if is_ca:
        write_text(ext_file,
                   "basicConstraints=critical,CA:TRUE\n"
                   "keyUsage=critical,keyCertSign,cRLSign\n")
    else:
        write_text(ext_file,
                   "basicConstraints=critical,CA:FALSE\n"
                   "keyUsage=critical,digitalSignature\n"
                   "extendedKeyUsage=codeSigning\n")

    run([
        openssl, "req", "-newkey", "rsa:2048", "-sha256", "-nodes",
        "-keyout", key_pem, "-out", csr_pem, "-subj", "/CN=" + common_name,
    ])
    run([
        openssl, "x509", "-req", "-in", csr_pem, "-sha256", "-days", "3650",
        "-CA", ca_cert, "-CAkey", ca_key, "-CAcreateserial",
        "-extfile", ext_file, "-out", cert_pem,
    ])
    run([openssl, "x509", "-in", cert_pem, "-outform", "DER", "-out", cert_der])
    return key_pem, cert_pem, read_file(cert_der)


def sbsign_image(sbsign, key_pem, cert_pem, in_path, out_path, addcert=None):
    """Append a WIN_CERTIFICATE signature to in_path, writing the result to out_path.

    If addcert is given (a PEM file of extra certificates), those certificates
    are embedded in the signature so a verifier can build the full chain.
    """
    cmd = [sbsign, "--key", key_pem, "--cert", cert_pem]
    if addcert is not None:
        cmd += ["--addcert", addcert]
    cmd += ["--output", out_path, in_path]
    run(cmd)


def authenticode_sha256(data):
    """Compute the Authenticode SHA-256 digest of a PE/COFF image.

    This mirrors the hashing performed by SecurityPkg's DxeImageVerificationLib
    (HashPeImage): the optional-header checksum field and the Certificate Table
    data directory entry are skipped, the sections are hashed in
    PointerToRawData order, and the attribute certificate table at the end of
    the file is excluded. The digest is therefore identical for the unsigned,
    signed, and dual-signed forms of the same image.
    """
    if data[0:2] != b"MZ":
        raise ValueError("not a PE image (missing MZ header)")
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe + 4] != b"PE\x00\x00":
        raise ValueError("not a PE image (missing PE signature)")

    coff = pe + 4
    num_sections = struct.unpack_from("<H", data, coff + 2)[0]
    size_opt = struct.unpack_from("<H", data, coff + 16)[0]
    opt = coff + 20
    magic = struct.unpack_from("<H", data, opt)[0]
    if magic == 0x10B:        # PE32
        datadir = opt + 96
    elif magic == 0x20B:      # PE32+
        datadir = opt + 112
    else:
        raise ValueError(f"unknown optional header magic 0x{magic:04x}")

    checksum_off = opt + 64
    size_of_headers = struct.unpack_from("<I", data, opt + 60)[0]
    cert_dir = datadir + 4 * 8        # Certificate Table is data directory index 4
    cert_size = struct.unpack_from("<I", data, cert_dir + 4)[0]

    sha = hashlib.sha256()
    sha.update(data[0:checksum_off])                 # start .. checksum field
    sha.update(data[checksum_off + 4:cert_dir])      # checksum .. cert table entry
    sha.update(data[cert_dir + 8:size_of_headers])   # cert table entry .. end of headers
    hashed = size_of_headers

    sections = []
    for i in range(num_sections):
        base = opt + size_opt + i * 40
        raw_size = struct.unpack_from("<I", data, base + 16)[0]
        raw_ptr = struct.unpack_from("<I", data, base + 20)[0]
        sections.append((raw_ptr, raw_size))
    for raw_ptr, raw_size in sorted(sections):
        if raw_size == 0:
            continue
        sha.update(data[raw_ptr:raw_ptr + raw_size])
        hashed += raw_size

    trailing_end = len(data) - cert_size
    if trailing_end > hashed:
        sha.update(data[hashed:trailing_end])

    return sha.digest()


def build_arch_file(output_dir, file_name, arch_label, image_path,
                    leaf_key, leaf_cert, chain_pem,
                    signer2_key, signer2_cert,
                    certs, sbsign, workdir):
    """Sign one architecture's image and emit its test-data C file.

    The signed image is signed by the leaf certificate with the intermediate +
    root chain embedded; the dual-signed image additionally carries signer 2's
    signature. The architecture-independent certificates (leaf, intermediate,
    root, signer 2) are emitted alongside the images/digests so each arch file
    is fully self-contained; only one arch file is compiled per build, so there
    is no duplicate-definition conflict.

    The generated file is written beneath output_dir using the provided file
    name relative path.
    """
    unsigned = read_file(image_path)
    signed_path = os.path.join(workdir, arch_label + ".signed.efi")
    dual_path = os.path.join(workdir, arch_label + ".dual.efi")

    sbsign_image(sbsign, leaf_key, leaf_cert, image_path, signed_path, addcert=chain_pem)
    sbsign_image(sbsign, signer2_key, signer2_cert, signed_path, dual_path)

    signed = read_file(signed_path)
    dual = read_file(dual_path)

    arrays = [
        ("mUnsignedImage", f"unsigned {arch_label} PE/COFF image", unsigned),
        (
            "mSignedImage",
            f"{arch_label} PE/COFF image signed by the leaf cert (chain embedded)",
            signed,
        ),
        (
            "mDualSignedImage",
            f"{arch_label} PE/COFF image signed by the leaf cert and signer 2",
            dual,
        ),
        (
            "mUnsignedImageDigest",
            "Authenticode SHA-256 digest of the unsigned image",
            authenticode_sha256(unsigned),
        ),
        (
            "mSignedImageDigest",
            "Authenticode SHA-256 digest of the signed image",
            authenticode_sha256(signed),
        ),
        (
            "mDualSignedImageDigest",
            "Authenticode SHA-256 digest of the dual-signed image",
            authenticode_sha256(dual),
        ),
    ]
    arrays += certs
    write_c_file(os.path.join(output_dir, file_name), arrays)


def main():
    """Parse arguments, generate signed image artifacts, and emit test data C files."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    arch_files = {
        "X64": os.path.join("X64", "TestData.c"),
        "AArch64": os.path.join("Aarch64", "TestData.c"),
    }

    parser = argparse.ArgumentParser(
        description=(
            "Sign unsigned EFI images, generate signed and dual-signed test variants, "
            "compute Authenticode SHA-256 digests, and emit X64/TestData.c and/or "
            "Aarch64/TestData.c for ImageValidationTestApp."
        ),
        epilog=(
            "Provide at least one of --x64-image or --aarch64-image. "
            "Requires openssl and sbsign on PATH unless overridden with --openssl "
            "and --sbsign."
        ),
    )
    parser.add_argument("--x64-image", help="Unsigned X64 PE/COFF EFI image to sign.")
    parser.add_argument("--aarch64-image", help="Unsigned AARCH64 PE/COFF EFI image to sign.")
    parser.add_argument("--output-dir", default=script_dir,
                        help="Directory to write the generated C files (default: this directory).")
    parser.add_argument("--openssl", help="Path to the openssl executable (default: search PATH).")
    parser.add_argument("--sbsign", help="Path to the sbsign executable (default: search PATH).")
    parser.add_argument("--workdir",
                        help=(
                            "Directory for intermediate keys / signed images "
                            "(default: a temporary directory)."
                        ))
    parser.add_argument("--keep", action="store_true",
                        help=(
                            "Keep the intermediate artifacts instead of deleting "
                            "the temporary work directory."
                        ))
    args = parser.parse_args()

    images = []
    if args.x64_image:
        images.append(("X64", args.x64_image))
    if args.aarch64_image:
        images.append(("AArch64", args.aarch64_image))
    if not images:
        sys.exit("error: provide at least one of --x64-image / --aarch64-image")

    openssl = tool_path("openssl", args.openssl)
    sbsign = tool_path("sbsign", args.sbsign)

    created_workdir = args.workdir is None
    workdir = args.workdir or tempfile.mkdtemp(prefix="gentestdata_")
    os.makedirs(workdir, exist_ok=True)

    try:
        #
        # Build a certificate chain (root CA -> intermediate CA -> leaf) used to
        # sign the images, plus a second independent signer for dual-signing.
        #
        root_key, root_cert, root_der = generate_root_ca(
            openssl, workdir, "root", "ImageVerificationTestApp Test Root CA"
        )
        int_key, int_cert, int_der = generate_signed_cert(
            openssl, workdir, "intermediate",
            "ImageVerificationTestApp Test Intermediate CA",
            root_key, root_cert, is_ca=True
        )
        leaf_key, leaf_cert, leaf_der = generate_signed_cert(
            openssl, workdir, "leaf",
            "ImageVerificationTestApp Test Leaf Signer",
            int_key, int_cert, is_ca=False
        )
        signer2_key, signer2_cert, signer2_der = generate_signer(
            openssl, workdir, "signer2", "ImageVerificationTestApp Test Signer 2"
        )

        #
        # Chain PEM (intermediate + root) embedded in the leaf signature so a
        # verifier can build leaf -> intermediate -> root and match any of them
        # enrolled in db / dbx.
        #
        chain_pem = os.path.join(workdir, "chain.pem")
        write_text(chain_pem, read_text(int_cert) + read_text(root_cert))

        certs = [
            ("mLeafCert", "DER-encoded X.509 leaf signing certificate", leaf_der),
            ("mIntermediateCert", "DER-encoded X.509 intermediate CA certificate", int_der),
            ("mRootCert", "DER-encoded X.509 root CA certificate", root_der),
            ("mSigner2Cert", "DER-encoded X.509 certificate for signer 2", signer2_der),
        ]

        for arch_label, image_path in images:
            build_arch_file(args.output_dir, arch_files[arch_label], arch_label,
                            image_path, leaf_key, leaf_cert, chain_pem,
                            signer2_key, signer2_cert, certs, sbsign, workdir)
    finally:
        if created_workdir and not args.keep:
            shutil.rmtree(workdir, ignore_errors=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
