/** @file
  Declarations for the built-in test images and signature data consumed by the Image
  Validation unit test application.

  The definitions live in the per-architecture generated files, exactly one of which is
  compiled per build (selected by the INF [Sources.<arch>] sections).

  The images are architecture-specific because a PE/COFF header declares a machine type;
  LoadImage() rejects an image whose architecture does not match the running application.
  The signer certificates are architecture-independent but are emitted into each arch file
  so each file is self-contained. The blobs are generated by GenTestData.py and checked in
  so the tests remain self-contained and deterministic.

  Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef TEST_DATA_H_
#define TEST_DATA_H_

#include <Uefi.h>

//
// Built-in PE/COFF images.
//
extern CONST UINT8  mUnsignedImage[];
extern CONST UINTN  mUnsignedImageSize;

extern CONST UINT8  mSignedImage[];
extern CONST UINTN  mSignedImageSize;

extern CONST UINT8  mDualSignedImage[];
extern CONST UINTN  mDualSignedImageSize;

//
// Authenticode (SHA-256) digests of each image
//
extern CONST UINT8  mUnsignedImageDigest[];
extern CONST UINTN  mUnsignedImageDigestSize;

extern CONST UINT8  mSignedImageDigest[];
extern CONST UINTN  mSignedImageDigestSize;

extern CONST UINT8  mDualSignedImageDigest[];
extern CONST UINTN  mDualSignedImageDigestSize;

//
// Certificates for the signed and dual signed images:
// 
// Signer 1: The certificate chain for the signed image (root CA -> intermediate CA -> leaf).
// Signer 2: The certificate for the second signer, used for the dual-signed image
//
extern CONST UINT8  mLeafCert[];
extern CONST UINTN  mLeafCertSize;

extern CONST UINT8  mIntermediateCert[];
extern CONST UINTN  mIntermediateCertSize;

extern CONST UINT8  mRootCert[];
extern CONST UINTN  mRootCertSize;

extern CONST UINT8  mSigner2Cert[];
extern CONST UINTN  mSigner2CertSize;

#endif // TEST_DATA_H_
