# A workflow to build the EDKII packages in this repository using certain configurations.
#
##
# Copyright (c) Microsoft Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Package CI

on:
  workflow_call:
    inputs:
      package-config:
        description: >
          A YAML array of objects. Each object must have a "packages" key.
          All other keys are passed through to the output.
          Example:
            - packages: 'MdePkg,UefiCpuPkg'
              targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
              architectures: 'X64,AARCH64'
            - packages: 'ShellPkg'
              targets: 'DEBUG'
        type: string
        required: true
      container:
        description: A container image to run the build in when using a linux runner.
        type: string
        required: true
      python-version:
        description: Python version to use when not running in a container
        type: string
        required: false
        default: '3.12'

jobs:
  package-ci:
    runs-on: ${{ matrix.os }}

    container:
      image: ${{ matrix.container || null }}
      options: --security-opt seccomp=unconfined

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        container: ['', '${{ inputs.container }}']
        architectures: ['AARCH64,IA32,X64']
        toolchain: ['CLANGPDB']
        config: ${{ fromJson(inputs.package-config) }}

        exclude:
          # Exclude container builds on Windows
          - os: windows-latest
            container: '${{ inputs.container }}'
          # Exclude non-container builds on Ubuntu
          - os: ubuntu-latest
            container: ''
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Container Configuration
        if: ${{ matrix.container != null }}
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Setup Python ${{ inputs.python-version }}
        if: ${{ matrix.container == null }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: pip-requirements.txt
      
      - name: Install Python dependencies
        run: pip install -r pip-requirements.txt
      
      - name: EDK II Package CI
        id: package-ci
        uses: ./.github/actions/stuart-ci
        with:
          ci-config: '.pytool/CISettings.py'
          packages: ${{ matrix.config.packages }}
          targets: ${{ matrix.config.targets }}
          architectures: ${{ matrix.architectures }}
          toolchain: ${{ matrix.toolchain }}
          stuart-setup: 'true'
          stuart-ci-setup: 'false'
      
      - name: Upload CI build logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ci-logs-${{ matrix.config.packages }}-${{ matrix.config.targets }}-${{ matrix.os }}
          path: ${{ steps.package-ci.outputs.log-path }}
