# A workflow to build the EDKII packages in this repository using certain configurations.
#
##
# Copyright (c) Microsoft Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Package CI

on:
  workflow_call:
    inputs:
      package-config:
        description: >
          A YAML array of objects. Each object must have a "packages" key.
          All other keys are passed through to the output.
          Example:
            - packages: 'MdePkg,UefiCpuPkg'
              targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
              architectures: 'X64,AARCH64'
            - packages: 'ShellPkg'
              targets: 'DEBUG'
        type: string
        required: true
      container:
        description: A container image to run the build in when using a linux runner.
        type: string
        required: false
        default: ''
      python-version:
        description: Python version to use when not running in a container
        type: string
        required: false
        default: '3.12'
      runner:
        description: The type of runner to use for the CI build. Possible values are 'ubuntu-latest', 'windows-latest', and 'self-hosted'. Default is 'ubuntu-latest'.
        type: string
        required: false
        default: 'ubuntu-latest'
      stuart-pr-eval:
        description: Whether to run `stuart_pr_eval` to evaluate if any package tests should be run based on the changed files ('true' or 'false').
        type: boolean
        required: false
        default: false

jobs:
  package-ci:

    name: "${{ matrix.packages }} ${{ matrix.architectures }} ${{ matrix.targets }}"

    runs-on: ${{ inputs.runner }}

    container:
      image: ${{ inputs.container || null }}
      options: --security-opt seccomp=unconfined

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.package-config) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
    
      - name: Setup Python ${{ inputs.python-version }}
        if: ${{ inputs.container == null }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: pip-requirements.txt

      - name: Install Python dependencies
        run: pip install -r pip-requirements.txt
      
      - name: Check if ${{ matrix.packages }} needs testing
        id: filter-packages
        if: ${{ inputs.stuart-pr-eval && github.event_name == 'pull_request'}}
        shell: bash
        run: >
          stuart_pr_eval
            -c ${{ inputs.ci-config }} 
            -t ${{ matrix.targets }}
            --pr-target ${{ github.base_ref }}
            --output-count-format-string "echo count={pkgcount} >> $GITHUB_OUTPUT"
      - name: log PR eval result
        if: ${{ inputs.stuart-pr-eval && github.event_name == 'pull_request'}}
        run: echo "PR evaluation determined that ${{ steps.filter-packages.outputs.count }} packages need testing."

      - name: Container Configuration
        if: ${{ inputs.container != null }}
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: EDK II Package CI
        id: package-ci
        uses: ./.github/actions/stuart-ci
        with:
          ci-config: '.pytool/CISettings.py'
          packages: ${{ matrix.packages }}
          targets: ${{ matrix.targets }}
          architectures: ${{ matrix.architectures }}
          toolchain: ${{ matrix.toolchain }}
          stuart-setup: 'true'
          stuart-ci-setup: 'false'
      
      - name: Upload CI build logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ci-logs-${{ matrix.packages }}-${{ matrix.architectures }}-${{ matrix.targets }}-${{ inputs.runner }}
          path: ${{ steps.package-ci.outputs.log-path }}
