# A workflow to build the EDKII packages in this repository using certain configurations.
#
##
# Copyright (c) Microsoft Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Package CI

on:
  workflow_dispatch:
  push:
    branches:
      - release/202511
  pull_request:
    branches:
      - release/202511

jobs:
  gather-packages:
    name: Gather Repository Packages
    uses: ./.github/workflows/gather-packages.yml
    with:
      package-config: |
        - packages: 'ArmPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'ArmPlatformPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'CryptoPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'DynamicTablesPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'EmbeddedPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'FatPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'FmpDevicePkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'IntelFsp2Pkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'IntelFsp2WrapperPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'MdeModulePkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'MdePkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'NetworkPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'PcAtChipsetPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'PolicyServicePkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'PrmPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'SecurityPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'ShellPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'StandaloneMmPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'UefiCpuPkg'
          targets: 'DEBUG,RELEASE'
        - packages: 'UnitTestFrameworkPkg'
          targets: 'DEBUG,RELEASE'
      default-config: |
        targets: 'DEBUG,RELEASE'

  package-ci:
    name: "[${{ matrix.config.packages }}] [${{ matrix.config.targets }}] [${{ matrix.architectures }}] (${{ matrix.os }})"

    needs: gather-packages

    runs-on: ${{ matrix.os }}

    container:
      image: ${{ matrix.container || null }}
      options: --security-opt seccomp=unconfined

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        container: ['', 'ghcr.io/microsoft/mu_devops/ubuntu-24-test:latest']
        architectures: ['AARCH64,IA32,X64']
        toolchain: ['CLANGPDB']
        config: ${{ fromJson(needs.gather-packages.outputs.packages) }}

        exclude:
          # Exclude container builds on Windows
          - os: windows-latest
            container: 'ghcr.io/microsoft/mu_devops/ubuntu-24-test:latest'
          # Exclude non-container builds on Ubuntu
          - os: ubuntu-latest
            container: ''
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Container Configuration
        if: ${{ matrix.container != null }}
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Setup Python 3.12
        if: ${{ matrix.container == null }}
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: pip-requirements.txt
      
      - name: Install Python dependencies
        run: pip install -r pip-requirements.txt
      
      - name: EDK II Package CI
        id: package-ci
        uses: ./.github/actions/package-ci
        with:
          ci-config: '.pytool/CISettings.py'
          packages: ${{ matrix.config.packages }}
          targets: ${{ matrix.config.targets }}
          architectures: ${{ matrix.architectures }}
          toolchain: ${{ matrix.toolchain }}
          stuart-setup: 'true'
          stuart-ci-setup: 'false'
      
      - name: Upload CI build logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ci-logs-${{ matrix.config.packages }}-${{ matrix.config.targets }}-${{ matrix.architectures }}-${{ matrix.os }}
          path: ${{ steps.package-ci.outputs.log-path }}
